// $Id$
/**
* Copyright (C) 2015 EDIT
* European Distributed Institute of Taxonomy
* http://www.e-taxonomy.eu
*
* The contents of this file are subject to the Mozilla Public License Version 1.1
* See LICENSE.TXT at the top of this package for the full license terms.
*/
package eu.etaxonomy.cdm.vaadin.view.dbstatus;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.data.Container;
import com.vaadin.ui.AbsoluteLayout;
import com.vaadin.ui.Button;
import com.vaadin.ui.ComboBox;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.Label;
import com.vaadin.ui.TwinColSelect;
import com.vaadin.ui.Window;

import eu.etaxonomy.cdm.model.common.TermVocabulary;
import eu.etaxonomy.cdm.vaadin.container.TaxonNodeContainer;
import eu.etaxonomy.cdm.vaadin.presenter.dbstatus.settings.SettingsPresenter;

/**
 * @author alex
 * @date 22.04.2015
 *
 */
public class SettingsConfigWindow extends CustomComponent {

    /*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	private static final long serialVersionUID = -8220442386869594032L;
	@AutoGenerated
    private AbsoluteLayout mainLayout;
    @AutoGenerated
    private Label label_4;
    @AutoGenerated
    private TwinColSelect distStatusSelect;
    @AutoGenerated
    private Label label_3;
    @AutoGenerated
    private Label label_2;
    @AutoGenerated
    private ComboBox distAreaBox;
    @AutoGenerated
    private ComboBox taxoNodeBox;
    @AutoGenerated
    private Button okButton;
    @AutoGenerated
    private Button cancelButton;
    @AutoGenerated
    private Label label_1;
    private final SettingsPresenter presenter;
    /**
     * The constructor should first build the main layout, set the
     * composition root and then do any custom initialization.
     *
     * The constructor will not be automatically regenerated by the
     * visual editor.
     */
    public SettingsConfigWindow() {
        buildMainLayout();
//        setCompositionRoot(mainLayout);
        presenter = new SettingsPresenter();
        init();
    }

    private void init() {
        Container taxonNodeContainer = new TaxonNodeContainer(null);
        Container distributionContainer = presenter.getDistributionContainer();
        TermVocabulary chosenArea = presenter.getChosenArea();
        taxoNodeBox.setItemCaptionPropertyId(TaxonNodeContainer.LABEL);
        taxoNodeBox.setContainerDataSource(taxonNodeContainer);
        taxoNodeBox.setValue(presenter.getChosenTaxonNode());
        distAreaBox.setContainerDataSource(distributionContainer);
        distAreaBox.setValue(chosenArea);
        distStatusSelect.setContainerDataSource(presenter.getDistributionStatusContainer());
    }

    public Window createWindow(){
        Window window = new Window();
        window.setModal(true);
        window.setHeight("600px");
        window.setWidth("500px");
        window.setCaption("Settings");
        window.setContent(mainLayout);
        return window;
    }

    @AutoGenerated
    private AbsoluteLayout buildMainLayout() {
        // common part: create layout
        mainLayout = new AbsoluteLayout();
        mainLayout.setImmediate(false);
        mainLayout.setWidth("100%");
        mainLayout.setHeight("100%");

        // top-level component properties
        setWidth("100.0%");
        setHeight("100.0%");

        // label_1
        label_1 = new Label();
        label_1.setImmediate(false);
        label_1.setWidth("100.0%");
        label_1.setHeight("40px");
        mainLayout.addComponent(label_1, "top:0.0px;left:0.0px;");

        // cancelButton
        cancelButton = new Button();
        cancelButton.setCaption("Cancel");
        cancelButton.setImmediate(true);
        cancelButton.setWidth("-1px");
        cancelButton.setHeight("-1px");
        mainLayout.addComponent(cancelButton, "top:380.0px;left:273.0px;");

        // okButton
        okButton = new Button();
        okButton.setCaption("OK");
        okButton.setImmediate(true);
        okButton.setWidth("67px");
        okButton.setHeight("-1px");
        mainLayout.addComponent(okButton, "top:380.0px;left:364.0px;");

        // classificationBox
        taxoNodeBox = new ComboBox();
        taxoNodeBox.setImmediate(false);
        taxoNodeBox.setWidth("-1px");
        taxoNodeBox.setHeight("-1px");
        mainLayout.addComponent(taxoNodeBox, "top:97.0px;left:258.0px;");

        // distAreaBox
        distAreaBox = new ComboBox();
        distAreaBox.setImmediate(false);
        distAreaBox.setWidth("-1px");
        distAreaBox.setHeight("-1px");
        mainLayout.addComponent(distAreaBox, "top:141.0px;left:258.0px;");

        // label_2
        label_2 = new Label();
        label_2.setImmediate(false);
        label_2.setWidth("-1px");
        label_2.setHeight("-1px");
        label_2.setValue("Classification/Taxon: ");
        mainLayout.addComponent(label_2, "top:97.0px;left:24.0px;");

        // label_3
        label_3 = new Label();
        label_3.setImmediate(false);
        label_3.setWidth("-1px");
        label_3.setHeight("-1px");
        label_3.setValue("Distribution Area:");
        mainLayout.addComponent(label_3, "top:141.0px;left:24.0px;");

        // distStatusSelect
        distStatusSelect = new TwinColSelect();
        distStatusSelect.setImmediate(false);
        distStatusSelect.setWidth("-1px");
        distStatusSelect.setHeight("-1px");
        mainLayout.addComponent(distStatusSelect, "top:188.0px;left:152.0px;");

        // label_4
        label_4 = new Label();
        label_4.setImmediate(false);
        label_4.setWidth("-1px");
        label_4.setHeight("-1px");
        label_4.setValue("Distribution Status:");
        mainLayout.addComponent(label_4, "top:202.0px;left:20.0px;");

        return mainLayout;
    }

}
