package eu.etaxonomy.cdm.vaadin.design.phycobank;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.Button;
import com.vaadin.ui.CssLayout;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.declarative.Design;

/**
 * !! DO NOT EDIT THIS FILE !!
 *
 * This class is generated by Vaadin Designer and will be overwritten.
 *
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class DashBoardDesign extends VerticalLayout {
    protected CssLayout dashboard;
    protected Button buttonNew;
    protected Button buttonConinue;
    protected Button buttonList;

    public DashBoardDesign() {
        Design.read(this);
    }
}
