// $Id$
/**
 * Copyright (C) 2015 EDIT
 * European Distributed Institute of Taxonomy
 * http://www.e-taxonomy.eu
 *
 * The contents of this file are subject to the Mozilla Public License Version 1.1
 * See LICENSE.TXT at the top of this package for the full license terms.
 */
package eu.etaxonomy.cdm.vaadin.component;

import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;

import org.apache.log4j.Logger;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.data.Container;
import com.vaadin.data.Property;
import com.vaadin.data.Property.ValueChangeEvent;
import com.vaadin.data.util.IndexedContainer;
import com.vaadin.data.util.sqlcontainer.RowId;
import com.vaadin.event.ItemClickEvent;
import com.vaadin.ui.Alignment;
import com.vaadin.ui.Button;
import com.vaadin.ui.CheckBox;
import com.vaadin.ui.ComboBox;
import com.vaadin.ui.Component;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.GridLayout;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.Table;
import com.vaadin.ui.Table.ColumnHeaderMode;
import com.vaadin.ui.TextField;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.themes.Reindeer;

import eu.etaxonomy.cdm.vaadin.view.IStatusComposite;

/**
 * @author cmathew
 * @date 11 Mar 2015
 *
 */
public class StatusComposite extends CustomComponent implements IStatusComposite {

    /*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

    @AutoGenerated
    private GridLayout mainLayout;
    @AutoGenerated
    private Table taxaTreeTable;
    @AutoGenerated
    private HorizontalLayout addRemovehorizontalLayout;
    @AutoGenerated
    private Button removeButton;
    @AutoGenerated
    private ComboBox addComboBox;
    @AutoGenerated
    private TextField searchTextField;
    @AutoGenerated
    private VerticalLayout filterVerticalLayout;
    @AutoGenerated
    private Table filterTable;
    @AutoGenerated
    private ComboBox filterComboBox;
    @AutoGenerated
    private ComboBox classificationComboBox;
    private static final Logger logger = Logger.getLogger(StatusComposite.class);
    private StatusComponentListener listener;

    private static final String SELECT_FILTER = "Select filter ...";
    private static final String SELECT_CLASSIFICATION = "Select classification ...";
    private static final String ADD_TAXON_SYNONYM = "Add ...";
    /**
     * The constructor should first build the main layout, set the
     * composition root and then do any custom initialization.
     *
     * The constructor will not be automatically regenerated by the
     * visual editor.
     */
    public StatusComposite() {
        buildMainLayout();
        setCompositionRoot(mainLayout);

        addUIListeners();
        initFilterNativeSelect();
        initFilterTable();
        initAddComboBox();
        setEnabledAll(false);
    }

    public void init() {
        initClassificationComboBox();

    }

    public void setEnabledAll(boolean enable) {
        filterComboBox.setEnabled(enable);
        filterTable.setEnabled(enable);
        taxaTreeTable.setEnabled(enable);
        addComboBox.setEnabled(enable);
        removeButton.setEnabled(enable);
    }

    private void initTaxaTable(int classificationId) {

        if(listener != null) {
            List<String> columnIds = new ArrayList<String>();
            columnIds.add("Name");
            taxaTreeTable.setColumnExpandRatio("Name", 1);
            columnIds.add("Pb");
            taxaTreeTable.setColumnWidth("Pb", 10);
            taxaTreeTable.addGeneratedColumn("Pb", new BooleanCheckBoxGenerator());
            try {
                taxaTreeTable.setContainerDataSource(listener.loadTaxa(classificationId), columnIds);
            } catch (SQLException e) {
                // TODO Auto-generated catch block
                e.printStackTrace();
            }
        }
    }

    private void initClassificationComboBox() {

        classificationComboBox.setNewItemsAllowed(false);
        classificationComboBox.setNullSelectionAllowed(false);
        classificationComboBox.setImmediate(true);
        classificationComboBox.setItemCaptionPropertyId("titleCache");
        classificationComboBox.setInputPrompt(SELECT_CLASSIFICATION);
        if(listener != null) {
            try {
                classificationComboBox.setContainerDataSource(listener.loadClassifications());
            } catch (SQLException e) {
                // TODO Auto-generated catch block
                e.printStackTrace();
            }
        }
    }


    private void initFilterNativeSelect() {
        filterComboBox.setNullSelectionAllowed(false);
        filterComboBox.setImmediate(true);
        filterComboBox.addItem(SELECT_FILTER);
        filterComboBox.addItem("unplaced");
        filterComboBox.addItem("not finished");
        filterComboBox.addItem("published");
        filterComboBox.setValue(SELECT_FILTER);
    }


    private void initFilterTable() {
        filterTable.setNullSelectionAllowed(false);
        Container container = new IndexedContainer();
        container.addContainerProperty("filter", String.class, "");

        filterTable.setContainerDataSource(container);
        filterTable.setColumnHeaderMode(ColumnHeaderMode.HIDDEN);
        filterTable.addStyleName(Reindeer.TABLE_BORDERLESS);
        filterTable.setCellStyleGenerator(new Table.CellStyleGenerator() {

            private static final long serialVersionUID = -3363906932807556720L;

            @Override
            public String getStyle(Table source, Object itemId, Object propertyId) {
                return "removable";
            }
        });
    }

    private void initAddComboBox() {
        addComboBox.setNullSelectionAllowed(false);
        addComboBox.setImmediate(true);
        addComboBox.addItem(ADD_TAXON_SYNONYM);
        addComboBox.addItem("New Accepted Taxon");
        addComboBox.addItem("New Synonym");
        addComboBox.setValue(ADD_TAXON_SYNONYM);

    }
    private void addUIListeners() {
        addClassificationComboBoxListener();
        addFilterComboBoxListener();
        addFilterTableListener();
    }

    private void addClassificationComboBoxListener() {

        classificationComboBox.addValueChangeListener(new Property.ValueChangeListener() {

            private static final long serialVersionUID = 4196786323147791606L;

            @Override
            public void valueChange(ValueChangeEvent event) {
                if (classificationComboBox.getValue() != null) {
                    Object selected = classificationComboBox.getValue();
                    logger.info("selected : " + selected);
                    int classificationId = (Integer)((RowId)selected).getId()[0];
                    initTaxaTable(classificationId);
                    setEnabledAll(true);
                }
            }
        });
    }

    private void addFilterComboBoxListener() {
        filterComboBox.addValueChangeListener(new Property.ValueChangeListener() {

            private static final long serialVersionUID = 1314542578509878256L;

            @Override
            public void valueChange(ValueChangeEvent event) {
                if (filterComboBox.getValue() != null) {
                    String selected = (String)filterComboBox.getValue();
                    logger.info("selected : " + selected);
                    if(!selected.equals(SELECT_FILTER)) {
                        filterTable.addItem(new Object[]{selected}, filterTable.getItemIds().size() + 1);
                        filterComboBox.setValue(SELECT_FILTER);
                    }
                }
            }
        });
    }

    private void addFilterTableListener() {
        filterTable.addItemClickListener(new ItemClickEvent.ItemClickListener() {

            private static final long serialVersionUID = -4722168300711497739L;

            @Override
            public void itemClick(ItemClickEvent event) {
                filterTable.removeItem(event.getItemId());
            }}
        );
    }


    /* (non-Javadoc)
     * @see eu.etaxonomy.cdm.vaadin.view.IStatusComponent#setListener(eu.etaxonomy.cdm.vaadin.view.IStatusComponent.StatusComponentListener)
     */
    @Override
    public void setListener(StatusComponentListener listener) {
        this.listener = listener;
    }


    class BooleanCheckBoxGenerator implements Table.ColumnGenerator {
        /**
         * Generates the cell containing an open image when boolean is true
         */
        @Override
        public Component generateCell(Table source, Object itemId, Object columnId) {
            Property prop = source.getItem(itemId).getItemProperty(columnId);
            return new CheckBox(null, prop);
        }
    }


    @AutoGenerated
    private GridLayout buildMainLayout() {
        // common part: create layout
        mainLayout = new GridLayout();
        mainLayout.setImmediate(false);
        mainLayout.setWidth("320px");
        mainLayout.setHeight("840px");
        mainLayout.setMargin(true);
        mainLayout.setSpacing(true);
        mainLayout.setRows(6);

        // top-level component properties
        setWidth("320px");
        setHeight("840px");

        // classificationComboBox
        classificationComboBox = new ComboBox();
        classificationComboBox.setImmediate(false);
        classificationComboBox.setWidth("100.0%");
        classificationComboBox.setHeight("-1px");
        mainLayout.addComponent(classificationComboBox, 0, 0);

        // filterVerticalLayout
        filterVerticalLayout = buildFilterVerticalLayout();
        mainLayout.addComponent(filterVerticalLayout, 0, 1);
        mainLayout.setComponentAlignment(filterVerticalLayout, new Alignment(20));

        // searchTextField
        searchTextField = new TextField();
        searchTextField.setImmediate(false);
        searchTextField.setWidth("100.0%");
        searchTextField.setHeight("-1px");
        mainLayout.addComponent(searchTextField, 0, 2);
        mainLayout.setComponentAlignment(searchTextField, new Alignment(20));

        // addRemovehorizontalLayout
        addRemovehorizontalLayout = buildAddRemovehorizontalLayout();
        mainLayout.addComponent(addRemovehorizontalLayout, 0, 4);
        mainLayout.setComponentAlignment(addRemovehorizontalLayout, new Alignment(48));

        // taxaTreeTable
        taxaTreeTable = new Table();
        taxaTreeTable.setImmediate(false);
        taxaTreeTable.setWidth("100.0%");
        taxaTreeTable.setHeight("536px");
        mainLayout.addComponent(taxaTreeTable, 0, 5);
        mainLayout.setComponentAlignment(taxaTreeTable, new Alignment(20));

        return mainLayout;
    }

    @AutoGenerated
    private VerticalLayout buildFilterVerticalLayout() {
        // common part: create layout
        filterVerticalLayout = new VerticalLayout();
        filterVerticalLayout.setImmediate(false);
        filterVerticalLayout.setWidth("100.0%");
        filterVerticalLayout.setHeight("-1px");
        filterVerticalLayout.setMargin(false);

        // filterComboBox
        filterComboBox = new ComboBox();
        filterComboBox.setImmediate(false);
        filterComboBox.setWidth("100.0%");
        filterComboBox.setHeight("-1px");
        filterVerticalLayout.addComponent(filterComboBox);
        filterVerticalLayout.setComponentAlignment(filterComboBox, new Alignment(20));

        // filterTable
        filterTable = new Table();
        filterTable.setImmediate(false);
        filterTable.setWidth("100.0%");
        filterTable.setHeight("86px");
        filterVerticalLayout.addComponent(filterTable);
        filterVerticalLayout.setComponentAlignment(filterTable, new Alignment(48));

        return filterVerticalLayout;
    }

    @AutoGenerated
    private HorizontalLayout buildAddRemovehorizontalLayout() {
        // common part: create layout
        addRemovehorizontalLayout = new HorizontalLayout();
        addRemovehorizontalLayout.setImmediate(false);
        addRemovehorizontalLayout.setWidth("100.0%");
        addRemovehorizontalLayout.setHeight("-1px");
        addRemovehorizontalLayout.setMargin(false);
        addRemovehorizontalLayout.setSpacing(true);

        // addComboBox
        addComboBox = new ComboBox();
        addComboBox.setImmediate(false);
        addComboBox.setWidth("100.0%");
        addComboBox.setHeight("-1px");
        addRemovehorizontalLayout.addComponent(addComboBox);
        addRemovehorizontalLayout.setExpandRatio(addComboBox, 3.0f);

        // removeButton
        removeButton = new Button();
        removeButton.setCaption("Remove");
        removeButton.setImmediate(true);
        removeButton.setWidth("100.0%");
        removeButton.setHeight("-1px");
        addRemovehorizontalLayout.addComponent(removeButton);
        addRemovehorizontalLayout.setExpandRatio(removeButton, 2.0f);

        return addRemovehorizontalLayout;
    }

}
